---
- name: Download Docker Compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Verify Docker Compose installation
  ansible.builtin.command: docker-compose --version
  register: compose_version
  changed_when: false

- name: Print Docker Compose version
  ansible.builtin.debug:
    msg: "{{ compose_version.stdout }}"

